#TEST
sport01 = {"sub-category01":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category02":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category03":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category04":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category05":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category06":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
           }
sport02 = {"sub-category01":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category02":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category03":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category04":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category05":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category06":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
           }
sport03 = {"sub-category01":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category02":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category03":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category04":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category05":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
                "sub-category06":
                  {"info01":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info02":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info03":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                    "info04":
                       ["sub-info01",
                        "sub-info02",
                        "sub-info03",
                        "sub-info04",],
                   },
           }
